# Generated by Django 4.0.5 on 2022-06-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='grad_year',
            field=models.CharField(max_length=4),
        ),
    ]
