# Generated by Django 4.0.5 on 2022-06-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_alter_record_grad_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='address',
            field=models.TextField(default='address', max_length=500),
        ),
        migrations.AddField(
            model_name='record',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
