# Generated by Django 4.0.5 on 2022-06-28 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_record_address_record_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='photo',
        ),
    ]
