# Generated by Django 4.0.5 on 2022-06-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_remove_record_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='mobile_no',
            field=models.CharField(default='+91 98765 43210', max_length=15),
        ),
    ]
